service: perfsys-cloud-crm-ui

plugins:
  - serverless-scriptable-plugin
  - serverless-s3-sync

custom:
  bucketName: perfsys-cloud-crm-ui-${opt:stage, 'dev'}
  s3Sync:
    - bucketName: ${self:custom.bucketName}
#      bucketPrefix: dist/
      localDir: dist

  scriptHooks:
    before:deploy:createDeploymentArtifacts: node_modules/.bin/cross-env S3_UPDATES_DATA_BUCKET=${cf:perfsys-cloud-crm-api-${self:provider.stage}.S3DataUploadBucketName} API_BASE_URL=${cf:perfsys-cloud-crm-server-${opt:stage, 'dev'}.ServiceEndpoint}  IDENTITY_POOL_ID=${cf:perfsys-cloud-crm-api-${self:provider.stage}.UnAuthCognitoIdentityPool} REGION=${self:provider.region} npm run build

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

  environment:
    UI_DIST_BUCKET_NAME: ${self:custom.bucketName}

resources:
  Resources:
    S3UIDistBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.bucketName}
        WebsiteConfiguration:
          IndexDocument: index.html

    S3UIDistBucketBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: S3UIDistBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource:
                Fn::Join:
                 - ""
                 - - "arn:aws:s3:::"
                   - Ref: S3UIDistBucket
                   - "/*"

  Outputs:
    S3UIDistBucketName:
      Value:
        "Ref": "S3UIDistBucket"
      Export:
        Name:
          "Fn::Join":
            - ':'
            -
              - Ref: 'AWS::StackName'
              - 'S3UIDistBucketName'

    S3UIDistBucketArn:
      Value:
        "Fn::GetAtt": ["S3UIDistBucket", "Arn" ]
      Export:
        Name:
          "Fn::Join":
            - ':'
            -
              - Ref: 'AWS::StackName'
              - 'S3UIDistBucketArn'

    S3UIDistBucketArnMask:
      Value:
        Fn::Join:
         - ""
         - - "Fn::GetAtt": ["S3UIDistBucket", "Arn" ]
           - "/*"
      Export:
        Name:
          "Fn::Join":
            - ':'
            -
              - Ref: 'AWS::StackName'
              - 'S3UIDistBucketArnMask'

    S3UIDistBucketWebsiteURL:
      Value:
        Fn::Join:
         - ""
         - - "Fn::GetAtt": ["S3UIDistBucket", "WebsiteURL" ]
           - "/*"
      Export:
        Name:
          "Fn::Join":
            - ':'
            -
              - Ref: 'AWS::StackName'
              - 'S3UIDistBucketWebsiteURL'
